### PR TITLE
Fix plural issue with lang-region locale

### LINKED ISSUE #256: Adding count to t options throws error at computeDerivedKeys and causes webpack build to fail
**Describe the bug**

Webpack build is failing when specifying the `count` property in a `t` call. If I remove `count` then the strings get extracted correctly. When using webpack devserver+HMR webpack gets stuck in an infinite error loop.

The language code shown in the error message is not always `en-US`, the other common code I see is `my` but it's not consistent.

Error: /Users/....../MyComponent.js: Unknown locale 'en-US'.
    at computeDerivedKeys (/Users/....../node_modules/babel-plugin-i18next-extract/index.js:1798:32)
    at /Users/....../node_modules/babel-plugin-i18next-extract/index.js:1970:103
    at Array.reduce (<anonymous>)
    at PluginPass.post (/Users/....../node_modules/babel-plugin-i18next-extract/index.js:1970:56)
    at transformFile (/Users/....../node_modules/@babel/core/lib/transformation/index.js:85:27)
    at transformFile.next (<anonymous>)
    at run (/Users/....../node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/Users/....../node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/Users/....../node_modules/gensync/index.js:261:32)
    at /Users/....../node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/....../node_modules/gensync/index.js:223:11)

**How to reproduce**

Error occurs when I add a `count` property to the `t` options.

*Babel configuration:*

```
[
    "i18next-extract",
    {
        locales: [
    "en",
    "en-US",
    "en-GB",
    "ar",
    "zh-CN",
    "zh-HK",
    "cs-CZ",
    "cy",
    "da",
    "nl",
    "fi",
    "fil",
    "fr-CA",
    "fr-FR",
    "de",
    "he",
    "hi",
    "hu",
    "id",
    "it",
    "ja",
    "ko",
    "no",
    "pl",
    "pt",
    "pt-BR",
    "ro",
    "ru",
    "sk",
    "es-MX",
    "es",
    "sv",
    "te",
    "tr",
    "vi",
    "my",
    "th",
    "sw"
],
        useI18nextDefaultValue: true,
        useI18nextDefaultValueForDerivedKeys: true,
        enableExperimentalIcu: true,
        compatibilityJSON: "v4",
        jsonSpace: 2,
        outputPath: "locale/{{locale}}/{{ns}}.json"
    }
]
```

*Reproduction:*

```
t("mykey", {
      defaultValue: `{{count}} users`
      count: count
  })
```

**Your environment**

- OS: MacOS 13
- Plugin version: 0.9.0
- Babel version: 7.21.4
- Webpack version: 5.27.0
- Node version: 18.15.0

I'm note sure if there is something I'm missing in terms of extra modules or configuration required for plurals to work?

### PR DESCRIPTION
**Pull request by xu3u4**
To fix #256 

For {language}-{region} format locale, the plural count key can't be generated correctly.
The `locale` from the result of `pluralRule.resolvedOptions();` may only contain the language part, without the region.
Although the value of `locale` should be BCP 47 language tag, but node(only tested on v18.17) and some browsers don't support it yet. So I think we can also compare the language part of the locale.

On node v18.17
```js
const pluralRules = new Intl.PluralRules('en-US');
const options = pluralRules1.resolvedOptions();

console.log(options);
// output: Object { locale: "en", type: "cardinal",....}

```

### CODE REVIEW

**Comment by xu3u4** [comment]
Hi @gilbsgilbs 
May I have your review when you have time 🙏

**Comment by gilbsgilbs** [comment]
Thanks for the PR, I'll look into it ASAP. In the meantime, could you add a test for your fix?

**Comment by xu3u4** [comment]
Thank you for your suggestion 🙇‍♀️ , just added!

File: src/keys.ts [hunk 1]
```diff
@@ -153,7 +153,11 @@ export function computeDerivedKeys(
       throw unknownLocaleError;
     } else if (pluralRule instanceof Intl.PluralRules) {
       const pluralRulesOptions = pluralRule.resolvedOptions();
-      if (pluralRulesOptions.locale !== locale) {
+      const lang = locale.split('-')[0];
+      if (
```
Comment (gilbsgilbs) [inline src/keys.ts:157]: I'm wondering if we could/should be even more permissive. I think what we actually want to ensure here is that a plural rule was found for our current locale, not so much that the locale is consistent (because that would be a bug in i18next/Intl).

The comment above suggests that a pluralRule is always returned even for non-existing locales. Is there any property in the pluralRule or in the pluralRuleOptions that we could check to ensure i18next/Intl did resolve a locale and didn't fallback to whatever the default is? If so, I think I would prefer that we check that here instead of some convoluted heuristic. WDYT?

Comment (xu3u4) [reply src/keys.ts:157]: For case like `const pluralRule = new Intl.PluralRules('en-US');`
The locale from `pluralRule.resolvedOptions()` ideally should be `en-US`(BCP 47 language tag) based on the spec. ([ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/resolvedOptions))
But different browser and node return different result:
```
// chrome 119, node 18
locale: "en" 
// firefox 119
locale: "en-US"
```
It is possible that node return locale: "en-US" in the future, so I think we can allow `en` and `en-US` at the moment. 

Also, the output of resolvedOptions looks like
`{ locale: "en", type: "cardinal", minimumIntegerDigits: 1, minimumFractionDigits: 0, maximumFractionDigits: 3, pluralCategories: Array ["one", "other"], roundingIncrement: 1, roundingMode: "halfExpand", roundingPriority: "auto", trailingZeroDisplay: "auto" }`. No other property shows the default/fallback locale for it...

Comment (gilbsgilbs) [reply src/keys.ts]: gotcha, thank you for the explanation.

**Comment by xu3u4** [comment]
@gilbsgilbs 
I see your change. Using startWith looks good.
Thank you very much.

**Comment by gilbsgilbs** [comment]
I'll make a release later this week, probably tonight or tomorrow. I want to do some chore before releasing (mainly update dependencies, drop EOLed node versions and officially support newer node versions).

**Comment by gilbsgilbs** [comment]
Just published it under the 0.9.1 tag on NPM. Thank you again for your contribution, that's appreciated.
